// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkuyftkkeewamxxwefzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrdXlmdGtrZWV3YW14eHdlZnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDg4NDEsImV4cCI6MjA3MDIyNDg0MX0.DiLLNIB0ZhCAIF6TWx80ipnUFZf5p3p42kDRy3Pdmi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});